### PR TITLE
Added nmake based build

### PR DESCRIPTION
**Pull request by apnadkarni**
I have added the win directory to support building ffidl with nmake + Visual C++ (Visual Studio 2017). Some minor edits to ffidl.c which should be safe (couple of compiler warnings for VC++) but do not have the means to test on other platforms.

Passes the tests

### CODE REVIEW

**Comment by medranocalvo** [comment]
Thank you very much!

I'm going on holiday tomorrow, will review and merge in January.

Regards,
Adrián.

**Comment by apnadkarni** [comment]
Note: the fix for spaces in file paths is independent of the nmake build and applies to all platforms.

**Comment by medranocalvo** [comment]
I'm back.  Will review in the next few days.  Thanks!

**Comment by medranocalvo** [comment]
Still pretty busy, but not forgetting.  Will merge as soon as I find time.  Thank you again for the contribution and also for your patience.

**Comment by medranocalvo** [comment]
Hello @apnadkarni, finally have had a chance to look at this.

I have merged your changes and released 0.9b0.

At the same time, I have also released 0.8, with some changes from 0.8b0 which have been internal up to now.  In particular there have been some changes to the autoconf/make buildsystem, so I'd like to ask you to please review them.  The following might affect the NMake build:

  - https://github.com/prs-de/ffidl/commit/6d86fa178e676a6f1ab9571eefb8830d8ce50f9b,
  - https://github.com/prs-de/ffidl/commit/7491cc733891dcce0c6f536a8422d78efc73e2d1, and
  - https://github.com/prs-de/ffidl/commit/2974a95fd83423c421a7f84be326b51bc6f464f8.

I'm not sure whether I should state your copyright all around or not.  Given that most of your changes were to the build system I have not done it. Let me know how you prefer that to be handled, or update the PR with your preferences.

Thank you again.

**Comment by apnadkarni** [comment]
Sorry for the late response. Was out on summer vacation.

Re. copyright, I really don't think it is necessary to have my copyright. If I have inadvertently included it in some file, please feel free to remove it.

I'll look at 0.8 and 0.9b0 at some point in the future (hopefully near future). My long vacation means stuff piled up at work and my other open source projects :-)

/Ashok

**Pull request merged**
